gnosis/dex-liquidity-provision

- scripts/bracket_orders.js
- scripts/trading_strategy_helpers.js
This PR adds a check that warns the user when the price of dex.ag isn't close to the given price.
Partial remedy to issue #51.
> Add price check to order creation

- .travis.yml
- scripts/utils/printing_tools.js
- test/printingTools.js
There are many ad hoc scripts and workaround to represent ERC20 token amounts. This PR creates reliable tools to do exactly that.
First step towards solving issue #24.
> Add tools for printing representations of ERC20 token amounts

- truffle-config.js
> Fix compiler version for quicker testing

- scripts/compelete_liquidity_provision.js
- scripts/utils/internals.js
splitting order placement and funding transactions, since the merged t…ransaction does not fit into gas limit
testing plan:
```
npx truffle exec scripts/compelete_liquidity_provision.js --masterSafe=$MASTER_SAFE --fleetSize=20 --targetToken=1 --investmentTargetToken=1 --stableToken=7 --investmentStableToken=10 --targetPrice=238.05 --priceRangePercentage=15 --network=$NETWORK_NAME
```
> splitting order placement and funding transactions

- scripts/bracket_orders.js
- scripts/utils/internals.js
- scripts/utils/trading_strategy_helpers.js
- scripts/withdraw.js
- test/dfusionMultiSafes.js
Small refactoring.
The testfile seems to be completely new written, but I just added `describe(` clustering.
> Refactoring2

- scripts/bracket_orders.js
- scripts/utils/internals.js
- scripts/utils/trading_strategy_helpers.js
- scripts/withdraw.js
- test/dfusionMultiSafes.js
Small refactoring for less code duplication.
> Refactoring the deposit funcitonality

- scripts/utils/trading_strategy_helpers.js
The function fetching token info becomes much faster and caches previously queried tokens.
> Faster token info fetching

- scripts/utils/sign_and_send.js
> [Easy] clean up sign and send

- scripts/utils/sign_and_send.js
The web interface of the Gnosis Multisig has changed, and so has the link to the transaction page.
> Update Gnosis Multisig url

- scripts/utils/trading_strategy_helpers.js
- test/dfusionMultiSafes.js
This bug fixes the issue with the extra empty lines when running the tests.
> Remove leftover artifacts

- scripts/utils/trading_strategy_helpers.js
- test/dfusionMultiSafes.js
> ValidFrom fix

- scripts/utils/internals.js
- scripts/utils/trading_strategy_helpers.js
Avoid calls fetching the same contract instance multiple times.
> Reduce fetching of artifacts

- scripts/utils/trading_strategy_helpers.js
Add token instance that can be used in other functions interacting with ERC20 tokens.
> Add token instance to token object

- scripts/complete_liquidity_provision.js
- scripts/utils/internals.js
- scripts/utils/js_helpers.js
These are the improvements suggestions from yesterday's deployment session
> Deployment learnings

- test/dfusionMultiSafes.js
- test/test-utils.js
Creates two functions, `testManualDeposits` and `testAutomaticDeposits`, that allow to add deposit test cases more easily.
> Framework to test deposits

- scripts/README.md
- scripts/withdraw.js
> Consistent naming: transferBackToMaster -> transferFundsToMaster

- scripts/utils/trading_strategy_helpers.js
This is the last PR needed to get faster scripts by making good use of Javascript's neat async/await features.
> Faster transfer approve deposit

- scripts/utils/price-utils.js
- scripts/verify-correctness.js
- test/priceUtils.js
Adds the check that orders are not profitable for others
---
testplan:
```
npx truffle exec scripts/verify-correctness.js --masterSafe=$MASTER_SAFE --brackets 0xAB795A52D809e4A
a56da23b215Db7663d57CDE3A,0x45d8a3d10cd7Da86Dac21a51B305312Ebf80072d,0x2952bC69739c9534d09525ccCa33950F311CbE88,0x052253771E92a5Ff3c31163492b7e9101e0FC62f,0x90cBbcA16a0d1B802F575c179288B739d545b791,0xFcb1954Aff83F07dB5F3665349797BaD77A75c81,0xfAE2748F91525B7Dd7E9868c16f9Ad5a6EA5DE68,0x410f792da8a0a2e2f43f7b9317dA04E00F05D1AD,0xB498dB083e1E2c25A0d384f87a4D05eB7c05effC,0xB30D7400ab53cB81512629e26080127eFfb32c00,0xC5B24B4Dab763a44AFe57f66eE0074C2598E84ab,0x2cef9A8596aa983aD973bd5B8b5278F3AC83b789,0x1E800A7E4b103cA2C270e162E66d1B099eC8C1A7,0x65539d12c28946831D65Bb32eEc3A33CaBFB9249,0xD34AD431994192618E2E73867FA2B91eC2fA …
```
> Verifies that orders are not profitable for others

- .dockerignore
- Dockerfile
- README.md
- scripts/synthetix/facilicate_trade.js
- yarn.lock
This PR introduces a Dockerfile with a tiny linux image and the project dependencies required to run `facilitate_trade`. Observe that the network must be declared at the time of build, but the private key can be passed in dynamically.
**Testplan**
```sh
docker build --rm -t synthetix-orders .
docker run -e PK=$YOUR_PRIVATE_KEY -t synthetix-orders truffle exec scripts/synthetix/facilicate_trade.js --network rinkeby
```
> [Synthetix] Docker image for order placement script.

- scripts/bracket_orders.js
- scripts/utils/internals.js
- scripts/utils/verify_scripts.js
First of many PRs heeding the helpful recommendations of @cag in issue #142.
> Remove unnecessary instances of artifacts and web3

- contracts/test/EvilGnosisSafeProxy.sol
- package.json
- scripts/utils/internals.js
- scripts/utils/trading_strategy_helpers.js
- scripts/utils/verify_scripts.js
- test/verification_script.js
- yarn.lock
More checks for the verification script, as recommended by @cag in issue #142.
This includes:
- bytecode check for each bracket
- assert there are no modules, both in master and in each brackets
- assert fallback function is not set, both in master and in each brackets
> Verify script - bytecode, modules, and fallback function

- scripts/complete_liquidity_provision.js
- scripts/utils/trading_strategy_helpers.js
- scripts/utils/verify_scripts.js
- scripts/wrap_eth.js
- test/dfusion_multi_safes.js
- test/price_utils.js
- test/verification_script.js
The network is automatically retrieved when calling `.setProvider`.
> Use automatically retrieved network

- scripts/bracket_orders.js
- scripts/utils/trading_strategy_helpers.js
- test/dfusion_multi_safes.js
closes #148 
testplan:
unit tests
> use placeOrder instead of placeOrdersValidFrom

- scripts/README.md
- scripts/complete_liquidity_provision.js
- scripts/utils/sign_and_send.js
- scripts/utils/trading_strategy_helpers.js
- test/dfusion_multi_safes.js
- test/verification_script.js
This code would have caught my error and would have prevented false order placement.
testplan: unit tests only
> Verifying that no orders have been placed on the brackets beforehand

- scripts/complete_liquidity_provision.js
This log statement is valuable and had recently been removed.
> [Trivial] Replace lost console log

- test/dfusion_multi_safes.js
closes #123 
note that customized validFrom is no longer an option in the code.
> Testing order expiry of buildOrders

- package.json
- scripts/README.md
> Better documentation of needed programs

- scripts/README.md
- scripts/complete_liquidity_provision.js
- scripts/deploy_safes.js
- scripts/utils/sign_and_send.js
- scripts/utils/verify_scripts.js
- test/verification_script.js
Introducing the use of `verifyBracketsWellFormed` which asserts on many aspects of the provided bracket safes so to prevent any malicious activity. _Some_ facts regarding the bracket safes that are ensured here are
- that the owner of the brackets is the masterSafe
- that masterCopy of brackets is the known masterCopy
- proxy bytecode
- absence of modules
- unchanged fallback handler
If any of the above verification descriptions seem incomplete, please say so and suggest some improvements.
Closes #218 
```sh
git checkout 218/use_verifyBracketsWellFormed
export PK=0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
npx truffle exec scripts/complete_liquidity_provision.js --baseTokenId=1 --quoteTokenId=4 --lowestLimit=150 --highestLimit=200 --currentPrice=175 …
```
> Use verifyBracketsWellFormed in complete provision script

- scripts/README.md
> Correct withdraw file option

- scripts/utils/constants.js
- scripts/utils/internals.js
- scripts/utils/sign_and_send.js
- scripts/utils/trading_strategy_helpers.js
- test/test_utils.js
- test/verification_script.js
Move zero address constant to constant file. Note that constant was being exported from both `internals.js` and `trading_strategy_helpers.js`.
First step towards fixing issue with fallback handler on mainnet.
> Move zero address to constants file

- scripts/bracket_orders.js
- scripts/claim_withdraw.js
- scripts/request_withdraw.js
- scripts/transfer_approve_deposit.js
- scripts/transfer_funds_to_master.js
- scripts/wrap_eth.js
Partially a major problem of JS and our IDE, but also of lazy refactoring.
> [Easy] Outdated Imports (signAndSend)

- scripts/utils/trading_strategy_helpers.js
- test/scripts/deposit.js
Silly mistake, no need to return await
> Remove return await!

- migrations/2_dev_dependencies.js
- migrations/3_fleet_factory.js
- migrations/4_fleet_factory_deterministic.js
- networks.json
- scripts/testing/setup_thegraph_data.js
- scripts/utils/calculate_fleet_addresses.js
- scripts/utils/dependencies.js
- scripts/utils/verify_scripts.js
- test/dfusion_multi_safes.js
- test/fleet_factory.js
- test/fleet_factory_deterministic.js
- test/scripts/deposit.js
- test/scripts/test_airdrop.js
- test/scripts/withdraw.js
- test/verification_script.js
As #528 but this time for GnosisSafeProxyFactory
CI
> use packaged asset for GnosisSafeProxyFactory

- migrations/2_dev_dependencies.js
- networks.json
- scripts/utils/dependencies.js
- scripts/utils/internals.js
> [Easy] Use packaged MultiSend contract instead of local deployment
