scripts/utils/internals.js
closes #38 
There were two possible fixes for this issue:
Either:
-making sure that all infura nodes have synced with the current top of the chain(implemented) or - 
- using only one gnosis internal node
I have chosen the first one, as we don't want to require users to have access to a specific ethereum node.
The longterm fix is to deploy all safes in one transaction
=> Waiting shortly after deployment of safes in order to let infura nodes sync

scripts/complete_liquidity_provision.js, scripts/utils/internals.js, scripts/utils/trading_strategy_helpers.js, scripts/withdraw.js, test/dfusionMultiSafes.js
This PR removes some ad hoc functions we were using to handle token decimals and fixes a related bug in the withdraw scripts.
One step further in solving #24.
=> Use ERC20 printing functions in the code 

scripts/bracket_orders.js, scripts/utils/js_helpers.js, scripts/utils/trading_strategy_helpers.js, scripts/withdraw.js, test/dfusionMultiSafes.js
Drastically reduce the running time of the withdrawal scripts by heavily relying on Javascript's asynchronous features.
This PR is a test bench for using the same techniques everywhere else in this repo, so changes and recommendations are very welcome before we start working on the other scripts.
Notable breaking change is the function `fetchTokenInfo`, which is now split in `fetchTokenInfoAtAddresses` and `fetchTokenInfoFromExchange`, both of which return a promise.
Running times of withdraw.js
1. with two safes
- before: 28±1s
- after: 12±1s
2. with 20 safes
- before: 3min 6s (no ±, I ran it only once)
- after: 14.7±0.1s
Related issue: #57 
Thanks @nlordell for the discussion.
=> Faster withdrawal scripts

scripts/bracket_orders.js, scripts/complete_liquidity_provision.js, scripts/deploy_safes.js, scripts/transfer_approve_deposit.js, scripts/utils/internals.js, scripts/utils/price-utils.js, scripts/utils/sign_and_send.js, scripts/utils/trading_strategy_helpers.js, scripts/withdraw.js, scripts/wrap_eth.js, test/dfusionMultiSafes.js, test/priceUtils.js
Most functions' input is cluttered with `artifacts` and `web3`s. This PR remove most of them.
Instead of directly returning the functions we need, `require` is transformed into a function taking `web3` and `artifacts` as input. This input is then used by the imported functions without any need to inject it into the functions' arguments.
Not much is happening in this PR, most changes are indentation changes.
Still to do:
1. test that the scripts are working correctly.
=> Clean up artifacts and web3

scripts/bracket_orders.js, scripts/utils/internals.js, scripts/utils/trading_strategy_helpers.js
This applies the techniques from PR #72 to order creation.
We could prepare the orders while the user is deciding what to answer in the price check failed prompt. The reason I decided not to do it is logging: if I directly did that with the current code, the user would see the prompts and then information for each order being printed on top of the prompt.
Possible solutions are:
1. Separate order generation and order printing. With this solution we risk that the printed output doesn't match the real order.
2. Isolate the creation of order parameters is a single function and use this function directly to print order information. But this looked messy and redundant.
3. Return log as part of the output. This is very inconsistent with the rest of the code and should be done in case in a …
=> Optimize order creation

scripts/utils/internals.js, scripts/utils/trading_strategy_helpers.js, test/dfusionMultiSafes.js
closes #38 
Makes the function deploySafe return only the address of the freshly deployed contract
=> Less error prone safe deployments

scripts/utils/trading_strategy_helpers.js, scripts/withdraw.js
Change the way tokens are retrieved in deposits and use same strategy to send funds back to master.
Motivation: with the current deposit script we are calling `fetchTokenInfoFromAddresses` once for each deposit. If the token has not been retrieved before, then since all calls are run in parallel we have that each call creates its own promise for the token info at the same time, thus contacting the node multiple times for the same token.
=> Safer retrieval of tokens

package.json, test/dfusionMultiSafes.js, test/printingTools.js
This PR adds the BN library to the dependencies.
Since no version was specified we were using one of the versions provided by another package we are using. This old version accepts any string in the constructor, meaning that garbage would be returned when executing `new BN("1e10")`. With the newest version, the constructor fails on strings that are not well-formatted.
New tests for the printing tools are created to check for invalid strings. In the process I caught a related bug in the tests with automatic deposits and fixed it.
=> BN library as dependency

migrations/2_dev_dependencies.js, migrations/4_safe_migration.js
Safe contracts are currently also deployed on mainnet.
This PR moves them in the dev dependencies.
=> Deploy Safe contracts only on development network

contracts/Dependencies.sol, contracts/FleetFactory.sol, migrations/3_fleet_factory.js, test/fleetFactory.js
This PR introduces and tests an Ethereum contract (FleetFactory) for deploying multiple proxy Safes with a single function call in the EVM.
Advantages are:
1. reduced gas cost (a bit more than 21k gas for each Safe deployed)
2. shortened bracket deployment time
=> Create contract to deploy multiple proxy Safes in the same transaction

migrations/1_initial_migration.js, migrations/3_fleet_factory.js, networks.json, package.json, yarn.lock
Setup tools needed for a clean migration on mainnet, including contract verification on Etherscan.
Migrations are run as follows:
```
export NETWORK_NAME=<insert network name, e.g. rinkeby or mainnet>
export GAS_PRICE_GWEI=<insert gas price in Gwei, e.g. 20>
export PK=<insert Ethereum private key here>
export MY_ETHERSCAN_API_KEY=<insert Etherscan API key here>
rm -r build
yarn compile
yarn networks-inject
yarn migrate --network $NETWORK_NAME
yarn networks-extract
yarn verify FleetFactory --network $NETWORK_NAME
```
Contracts deployed on Rinkeby:
Migrations: `0xca39A48b3b0C8284bfF8f2299539e2BbaBE714de`
FleetFactory: `0x1b94BF378B910e5be70b59e774867a1c919821C7`
Contracts deployed on mainnet:
Migrations: `0x094419790e6bfD8071902C7DCa7D59F4c489bF0c`
FleetFactory: …
=> FleetFactory migration

scripts/bracket_orders.js, scripts/complete_liquidity_provision.js, scripts/deploy_safes.js, scripts/transfer_approve_deposit.js, scripts/utils/default_yargs.js, scripts/withdraw.js, scripts/wrap_eth.js
Reworks how command-line arguments are handled.
Most important change is that the scripts fail if one of the input arguments is not defined. This helps avoiding misspelling of arguments which would lead to some probably unwanted default behavior. Example: running the withdraw script with `--allToken` now fails (the right name is `--allTokens`).
=> Better argument hadling

.travis.yml, test/fleetFactory.js
This PR essentially used `truffle test` so that all test files are run rather than testing individual files. This change already revealed a file `fleetFactory` that was not being run in tests because of it. 
Have a generic test environment will avoid accidentally ignoring new files.
=> [Travis] Use generic truffle test

package.json
Finally a working fix for this dreadful `bitcore-lib` dependency by introducing a "resolution" version.
Test Plan:
Unfortunately I can only describe the test at this point. Worked for me when building a docker image of this project in #129. I recommend checking out that branch and observing that the build works with this, but not without!
=> [Easy] Bitcore Lib Fix

scripts/bracket_orders.js, scripts/complete_liquidity_provision.js, scripts/utils/price-utils.js, test/priceUtils.js
Motivation: I had an issue with a circular dependency in a PR I'm working on. I want to require price-utils from trading_strategy_helpers but the latter is already requiring the former. Since the only function needing that import is `isPriceReasonable`, and it looked like we could make it simpler, I removed the dependency by simplifying the logic. Is this change ok in your PR?
=> Remove import from price utils

package.json, scripts/utils/price-utils.js, scripts/utils/trading_strategy_helpers.js, test/dfusionMultiSafes.js, test/priceUtils.js, yarn.lock
I introduce two new functions:
1. `getOutputAmountFromPrice` computes how much stable token you get from the given price and target token amount.
2. `getUnlimitedOrderAmounts` computes the largest possible order you can make at a given price.
The goal of this PR is to reduce rounding error, especially when the number of decimals of the two traded tokens are significantly different from each other.
The PR is not yet complete: I'm still waiting for version `0.2.9` of `dex-contracts` to be published on npmjs.com. All tests pass on a local install.
=> Compute prices without precision issues

scripts/bracket_orders.js, scripts/complete_liquidity_provision.js, scripts/utils/internals.js, scripts/utils/printing_tools.js, scripts/utils/sign_and_send.js, scripts/utils/trading_strategy_helpers.js, scripts/utils/verify_scripts.js, test/dfusion_multi_safes.js, test/price_utils.js, test/test_utils.js, test/verification_script.js
While working on #137 I noticed that imports were messy.
This PR structures them as follows:
```
\\ external imports
\\ contracts/artifacts import
\\ internal imports, priority to those requiring web3 or artifacts
\\ constants
```
=> Reorganize imports

scripts/utils/trading_strategy_helpers.js, test/dfusion_multi_safes.js, test/verification_script.js
Currently, we can create orders for which the lowest limit is higher than the highest limit. Everything goes through smoothly and all brackets end up unprofitable, losing money from the point they receive funds.
This PR makes `buildOrder` fail in this scenario.
=> Fail order construction with bad limits

scripts/utils/price_utils.js, test/dfusion_multi_safes.js
This PR unearthed two issues in the function `checkCorrectnessOfDeposits`:
1. the function made no sense for tokens with digits!=18, yet no test failed because of that.
2. the function compared two BN using literal `<` and `>` instead of `.lt`, `.gt`.
Point 2. greatly aggravated my debugging of point 1.: when using `<` or `>` for comparison, the BNs are converted to strings and then lexicographically compared. This means that as long as the strings have the same length then the comparison works as expected, but if the length is different then it might yield unwelcomed surprises: for example, `"101"<"11" === true`.
I added a test case which would have failed with the code as it was before this PR and I rewrote the function to be, I hope, more straightforward. I would gladly accept comments …
=> Fix check deposits

scripts/utils/verify_scripts.js, test/verification_script.js
Another PR following the comments in issue #142. The logic of profitability checking is simplified, orders' token ids are checked, `Promise.all` is replaced with for loop since there are no asynchronous functions in this part of the code.
=> Verify script - better order checks

package.json, scripts/withdraw.js, scripts/wrapper/withdraw.js, test/scripts/withdraw.js, yarn.lock
Move the logic of the withdraw script to its own testable function. Tests are added.
This PR inadvertently fixed issue #78 for the withdraw script. Another PR should fix the issue for all scripts, otherwise we would have an incostistent behavior between scripts when managing filesystem paths.
=> Reorganize withdraw script

scripts/README.md
Just one typo in the "Use at your own risk" and a line break in example command.
=> [Easy] Readme Fix

scripts/transfer_approve_deposit.js
Fixes issue #78 and makes the behavior of the deposit script consistent with that of the withdraw script after PR #155. With this change, the command-line examples in the readme become correct.
=> Fix relative paths in deposit script

package.json, yarn.lock
Clean up of `package.json`.
Dependencies have been correctly sorted into dev and non-dev.
Unused package `run-with-testrpc` has been removed.
A nice addition that could also be included in dex-contracts is `engines`: if you try to run `yarn install` with for example Node version 11 the command fails telling the user the Node version is incompatible. I remember my first experience with `dex-contracts` was to debug a mysteriously failing installation due to the fact that the Node version I used was 12.
=> Rework package.json

scripts/withdraw.js, scripts/wrapper/withdraw.js, test/scripts/withdraw.js
The command-line options of the withdraw script are changed:
- `--allTokens` is removed;
- `--from` is introduced as an alternative to `--withdrawalFile` and accepts a comma-separated list of bracket addresses. Tokens to be withdrawn must be specified manually with one of two new command-line options: `--tokens` or `--tokenIds`, which take a list of addresses or ids respectively for the tokens to withdraw. Amounts are computed automatically.
Note that using a deposit file is more efficient, especially if only one token is deposited at each address. If there are n brackets and m tokens, then using a deposit file would cost `~n` web3 requests, while using `--from` takes `~nm` requests since it needs to retrieve the balances of each pair (token, bracket). Anyway, if the amount to withdraw is …
=> Withdraw without withdrawal file

scripts/utils/trading_strategy_helpers.js
Partially solves issues #74 and #120, further improvements require a different logging strategy. The logs are now printed if the flag `debug` is set to true, there are no repeating log lines, and the fetching message only appears if token info is actually being fetched from the EVM instead of retrieved locally.
=> Fix logging when fetching tokens

scripts/README.md, scripts/complete_liquidity_provision.js, scripts/utils/sign_and_send.js
This Pr calculates the nonce for the script: complete_liquidity_provision.
This allows us to smoothen the user workflow, as both tx are sent to the gnosis-interface simultaneously.
testplan:
try out the new feature like that:
```
npx truffle exec scripts/complete_liquidity_provision.js --targetToken=1 --stableToken=2 --lowestLimit=190 --highestLimit=215 --currentPrice=187 --masterSafe=$MASTER_SAFE --investmentTargetToken=0 --investmentStableToken=0 --fleetSize=20 --network=rinkeby
```
and make sure that you can sign both transactions in our rinkeby safe
=> Calculating the nonce

scripts/withdraw.js
One of the arguments of the withdraw script was not modified to reflect the changes in the wrapper done in PR #168. This PR fixes that.
=> Fix --brackets argument in withdraw script

scripts/complete_liquidity_provision.js
Part of the learning of the incident.
Because we were not waiting long enough, the scripts were failing and I was hardcoding the brackets manually.
=> Fix - longer waiting time, before creating the orders

package.json, yarn.lock
Similar to the changes made in dex-contracts, we pin this version of solidity data structures so that dependabot stops asking.
https://github.com/gnosis/dex-contracts/pull/704#pullrequestreview-403493548
Closes #172
=> [Easy] pin solidity data structures

contracts/Dependencies.sol, contracts/test/DetailedMintableToken.sol, package.json, yarn.lock
A new way to depend on OZ.
Note also that I have moved the `dev-dependencies` down in `package.json`
Very similar to https://github.com/gnosis/dex-contracts/pull/716, but notice that our `yarn.lock` still have traces of old versions of OZ. It appears that`gnosis-safe`, `chainlink` and `synthetix` all depend on them.
=> Use OpenZeppelin's npm package

package.json, scripts/synthetix/facilitate_trade.js, yarn.lock
We introduce a way to declare the desired gas price to send along with the orderplacement transaction  "gasPrice" and "gasPriceScale". 
Unfortunately, I had to revert a few recently bumped versions in order to run the latest docker image because of [this](https://github.com/trufflesuite/truffle/issues/3024#issuecomment-623663893) issue with `@truffle/contract`. Will promptly bump all the versions ASAP.
**Test Plan:**
```
truffle exec scripts/synthetix/facilitate_trade.js --network rinkeby --gasPrice fast --gasPriceScale 1.2
```
Expect to see something like this in the console logs
```
Using network 'rinkeby'.
Using account 0x627306090abaB3A6e1400e9345bC60c78a8BEf57
sETH Price 204.85369360931420279
Using current "fast" gas price scaled by 1.2: 12000000001 <------ This is new! …
```
=> Two new kwargs to snx-liqudity script

scripts/README.md, scripts/utils/sign_and_send.js
Closes #154 
This PR fixes in practice the gas limit to a value around 6m.
But we can not set the value straight forward, as Metamask still adds a gas-buffer.
testplan:
```
export PK...
source config/rinkeby.env
npx truffle exec scripts/complete_liquidity_provision.js --targetToken=1 --stableToken=2 --lowestLimit=190 --highestLimit=215 --currentPrice=207 --masterSafe=$MASTER_SAFE --investmentTargetToken=0 --investmentStableToken=0 --fleetSize=<Random even. number < 20 > --network=rinkeby
```
and check in meta mask the proposed gas, which should be around 6 million.
=> Fixed gas limit

scripts/utils/sign_and_send.js
#200 only works with 0x prefixed PKs. However truffle itself allows both prefixed and non-prefixed keys and when exporting from MM one would have to manually add the prefix.
This PR makes it so that the code works with both.
- export PK=0x...
- run script and see we can propose a tx
- export PK=... (without prefix)
- see this works as well
=> [Easy] allow PKs with both 0x and no prefix

scripts/utils/sign_and_send.js
Fixes #154 
Instead of hardcoding an internal gas limit (which already turned out to be brittle, cf #209), we should use the Safe's functionality to estimate the internal call appropriately.
This is also done in the [safe-proxy-kit](https://github.com/gnosis/contract-proxy-kit/pull/49/files) and an example of how to do it can be found in the safe contracts [unit tests](https://github.com/gnosis/safe-contracts/pull/188)
There are two tiny unrelated changes in this PR. One is a hotfix for #200 and the other one is a formatting issue that made only printed as:
> Error: Error while talking to the gnosis-interface: [object Object] 
```
export NETWORK_NAME=rinkeby
export GAS_PRICE_GWEI=9
export MASTER_SAFE=your master safe
export PK=...
npx truffle exec scripts/complete_liquidity_provision.js …
```
=> [GasEstimate] Use safe method to estimate gas for internal call

scripts/README.md, scripts/complete_liquidity_provision.js
This change allows users to specify the existing sub safes for use in the bracket strategy. Note that step numbers were removed because the logical ordering no longer makes sense.
Observe that the safes are required to be solely owned by master safe and the script will error out if this is not the case.
I made a few grammatical changes to the README while I was on this, will happily move it into a different PR.
closes #191
**Test Plan:**
This one will work, 
```
npx truffle exec scripts/complete_liquidity_provision.js --targetToken 1 --stableToken 4 --lowestLimit 200 --fleetSize 2 --highestLimit 216 --currentPrice 208 --masterSafe 0xd9395aeE9141a3Efeb6d16057c8f67fBE296734c --investmentTargetToken 0.1 --investmentStableToken 1 --network rinkeby …
```
=> Use existing brackets instead of new fleet (if desired)

package.json, scripts/wrapper/withdraw.js, test/scripts/withdraw.js, yarn.lock
Implements the changes described in #159.
When executing `withdraw.js` with `--brackets`:
- `--requestWithdraw` uses the maximum value for `uint256`. The idea is that a user who doesn't specify the amounts with a deposit file simply wants to withdraw everything in the brackets. Before this PR the script would only request to withdraw the amount that was available at the time of the request, meaning that amounts deriving from future trades would not be withdrawn. The new behavior is also useful for an emergency shutdown of the brackets.
- `--withdraw` and `--withdraw --transferFundsToMaster` compute the actual amount available for withdrawing. Before they relied on the amount specified in the withdraw request.
- `--transferFundsToMaster` is unchanged.
Downside of the changes is that the …
=> Change amount withdrawn with --brackets

scripts/utils/trading_strategy_helpers.js
I was unable to determine what "trades A against B" meant so I made this comment more descriptive. Note that it was still unclear in the code what, exactly, was being bought and sold in each so I invoked the famous phrase "buy low, sell high" philosophy here. Assuming `targetToken` is the volatile token, then `stableToken` is the reference point. This means then then target token is being bought for the lower price and sold at the higher price.
**Test plan:** Existing unit tests.
Closes #126
=> Rework confusing comment

scripts/bracket_orders.js, scripts/complete_liquidity_provision.js, scripts/transfer_approve_deposit.js, scripts/utils/sign_and_send.js, scripts/utils/user_interface_helpers.js, scripts/withdraw.js, scripts/wrap_eth.js
Changes here, move the user prompt into a more appropriate location which avoids being unavoidably imported multiple times in files that rely on it.
Closes #189 
Run this (with intentionally bad  values)
```sh
npx truffle exec scripts/complete_liquidity_provision.js --targetToken 1 --stableToken 4 --lowestLimit 300 --fleetSize 2 --highestLimit 416 --currentPrice 20 --masterSafe 0xd9395aeE9141a3Efeb6d16057c8f67fBE296734c --investmentTargetToken 0.1 --investmentStableToken 1 --network rinkeby --brackets=0x725fd170B9a8c28caabB9b81Dd0dC80Fb3aa5Db6,0xeda61B1e9f414889ddE0dbe83B3BaCF814A98E87
```
and expect to get the following warnings along with their "proceed Anyway" prompts.
```
Warning: the chosen price differs by more than 2 percent from the price found on dex.ag.
chosen price: 20 USDC …
```
=> Fix duplicated "y" in user prompt

scripts/utils/trading_strategy_helpers.js
Previously, we were taking advantage of some non-intuitive symmetric properties emitted by the `unlimitedOrderAmounts` function that were difficult to interpret. This PR simply uses the function directly as was intended rather than assuming any prior knowledge about the function's "special properties".
=> [Easy] Rework unlimited order function usage

scripts/README.md, scripts/bracket_orders.js, scripts/complete_liquidity_provision.js, scripts/utils/price_utils.js, scripts/utils/trading_strategy_helpers.js, test/dfusion_multi_safes.js, test/price_utils.js, test/verification_script.js
As discussed in the issue, we have chosen to with more commonly used language for our previously "target" and "stable" tokens. That is, we now use the more common, "quote" and "base" currencies for which "quote" is the one whose price is specified in relation to a "base" token. See [investopedia](https://www.investopedia.com/terms/b/basecurrency.asp) for discussion on the naming convention.
Note also that the term "investment" has been replaced with "deposit" and we now specify `TokenId` instead of just `Token` in the script arguments.
Closes #231
Test Plan:
In our case, since the brackets were originally meant to be between ETH and DAI, since we are always "quoting" the price of ETH in units of DAI, please see a few relevant changes in the comments that explicitly mention ETH and DAI to …
=> stable to quote & target to base

scripts/wrap_eth.js
Closes #238
Test Plan:
```sh
export PK=0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
npx truffle exec scripts/wrap_eth.js --masterSafe 0x8990c564ec303C7b26d3d5556ef0910E58Be08Ce --amount 10 --network rinkeby --dry-run
```
=> [Easy] BN was causing error in `gasEstimation` function.

scripts/complete_liquidity_provision.js
Running the complete liquidity provision script prints some scary lines:
```
==> Sending the [...] transaction. Attention: something something.
```
This PR suppresses the printing of these messages.
=> Remove sending logs when verifying

.gitignore
Some users might want to have a local `.env` file where they keep their script parameters like `PK` and `MASTER_SAFE` etc... This would allow people to ensure their .env files are untracked.
Sample file:
```
PK=0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d
MASTER_SAFE=0x8990c564ec303C7b26d3d5556ef0910E58Be08Ce
```
=> Do not track *.env

scripts/README.md, scripts/complete_liquidity_provision.js, scripts/deploy_safes.js, scripts/utils/trading_strategy_helpers.js, test/dfusion_multi_safes.js
This PR simply renames  `fleetSize` to `numBrackets` in all appropriate user facing locations.
Closes #253
Test Plan
```sh
npx truffle exec scripts/complete_liquidity_provision.js --baseTokenId=1 --quoteTokenId=4 --lowestLimit=150 --highestLimit=200 --currentPrice=175 --masterSafe=0x8990c564ec303C7b26d3d5556ef0910E58Be08Ce --depositBaseToken=0.1 --depositQuoteToken=10 --numBrackets=10 --network=rinkeby --dry-run
```
=> [Easy] Rename fleetSize -> numBrackets

scripts/bracket_orders.js, scripts/complete_liquidity_provision.js, scripts/utils/constants.js, scripts/utils/internals.js, scripts/utils/price_utils.js, scripts/utils/printing_tools.js, scripts/utils/trading_strategy_helpers.js, scripts/wrapper/withdraw.js, test/dfusion_multi_safes.js, test/price_utils.js, test/printing_tools.js, test/verification_script.js
Moves many of the constants defined in this repo into a single constant file.
Note that these constants are used for both scripts and tests, so if we get a constant wrong then the tests may not catch the ensuing errors.
I did not touch constants defined for the Synthetix script.
Note that this PR fixes a small bug that causes orders created with the order creation script to not have the same expiration date as those created with the complete liquidity provision script.
Closes #223.
=> Move constants to own file

scripts/README.md, scripts/claim_withdraw.js, scripts/request_withdraw.js, scripts/transfer_funds_to_master.js, scripts/wrapper/withdraw.js, test/scripts/withdraw.js
Split the withdraw script into two scripts: `request_withdraw.js` and `withdraw.js`.
All four logical steps in the script have now their own function. They are:
1. requesting a withdrawal
2. withdrawing from the exchange to the brackets
3. transferring ERC20 tokens from the brackets to master
4. simultaneous 2 and 3
Since I had to work on it anyway, I also changed the focus of the documentation from a deposit file to `--brackets` and `--tokenIds`.
PR is relevant to @josojo because it changes the tutorial on how to use the scripts.
Closes #222.
=> Split withdraw script

.travis.yml, README.md, package.json, scripts/README.md
Creates more yarn scripts to simplify setting up of the project and adds building artifacts to Travis.
Might be interesting to amend the tutorial with this new procedure, @josojo. (I could also do it instead.)
To test the new commands, check that [Travis is working as expected](https://travis-ci.com/github/gnosis/dex-liquidity-provision/builds/169430145) and try to reinstall this repo from scratch:
```
git clone https://github.com/gnosis/dex-liquidity-provision.git
cd dex-liquidity-provision
yarn install
yarn build
```
and then try to run any of the scripts in Rinkeby.
=> Simplify installation steps

scripts/utils/verify_scripts.js, test/verification_script.js
Reintroduces proxy bytecode verification. See discussion in issue #217.
Unrelated to this PR, but note that the verification script could be made much faster with the same simple tricks used in PR #286.
Closes #217.
Test plan: unit test for bytecode changes was restored.
On mainnet, this should be successful:
```
npx truffle exec scripts/verify_correctness.js  --network=mainnet --brackets=0x7c46953a4f0b404e21ebc0d69883adaef5aaa5c5 --masterSafe=0x5CC3a4C846aB8b0B78a729b8B1a50e2E0BB66740
```
and this should fail:
```
npx truffle exec scripts/verify_correctness.js  --network=mainnet --brackets=0xaafd977483df35bc90c27abbf96e6f7df5143013 --masterSafe=0x5CC3a4C846aB8b0B78a729b8B1a50e2E0BB66740
```
=> Fix bytecode check

scripts/synthetix/facilitate_trade.js, scripts/utils/printing_tools.js
Closes #282. 
This PR improves the synthetix script to only place order when there is a likely match according to the query from price estimation service. 
**Test Plan:**
Run
```sh
truffle exec scripts/synthetix/facilitate_trade.js --network mainnet
```
and observe the logs:
```
Using network 'mainnet'.
Using account 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
Oracle sETH Price (in sUSD) 243.3257626212688802
Exchange buy  sETH price (in sUSD) 246.6144973941891
Exchange sell sETH price (in sUSD) 233.72582778494302
Not placing buy  sETH order, our rate of 242.60 is too low  for exchange.
Not placing sell sETH order, our rate of 244.06 is too high for exchange.
```
On Rinkeby (i.e. where there is no s-liquidity), 
```sh
truffle exec scripts/synthetix/facilitate_trade.js --network rinkeby
``` …
=> [Synthetix] Place orders only when likely match

scripts/synthetix/facilitate_trade.js
This change simply checks the bots balance right before constructing the order to place. Note that the balance checks are only made if an order is about to be placed which saves some EVM calls. Also, the logs will be more coherent (stating that the order is about to be placed, but the balance was insufficient if this is the case while not mentioning the balance issue if it wasn't going to try and place an order anyway).
Closes #304
=> Verify trading account has sufficent sellToken

scripts/README.md
Just a quick fix of a typo for this README documentation
=> Fixed typo in README for place_orders

scripts/utils/trading_strategy_helpers.js
There was a tiny error with the parameter handover.
This PR fixes the issue.
Testplan:
See that a new deployment runs smoothly and no longer creates this error:
`Error: invalid number value (arg="validUntil", coderType="uint32", value=true)`
=> hotfix for parameter handover for order bundling

test/fleet_factory_deterministic.js
it hurts, but the promises in the test were not awaited.
Fortunately, at least the function was correct.
=> Correct one test of deterministic fleet deployment

scripts/utils/internals.js
Our current gas estimation expects eth.call to return a revert message, which contains the required amount of gas. This works on geth nodes, on parity however the reverted call causes an exception to be thrown which is not handled in the current code path. This PR adds handling and gas estimate extraction form the exception's error message.
xDAI only runs with parity nodes, so this is needed in order to get the scripts running on xDAI.
running complete liquidity provision on xDAI (next PR).
=> Support Parity Nodes for GasEstimation

networks.json, package.json, scripts/utils/default_yargs.js, scripts/utils/gnosis_safe_server_interactions.js, scripts/utils/internals.js, yarn.lock
This PR upates the dependencies to contain xDAI ready contracts and performs an xDAI migration.
```
yarn truffle migrate --network xdai
```
Note that the addresses for the Safe contracts (GnosisSafeProxyFactory, GnosisSafe, MultiSend) have been added to networks.json by hand, partially because of https://github.com/gnosis/safe-contracts/issues/231 and partially due to https://github.com/gnosis/dex-liquidity-provision/issues/517
```
yarn truffle exec scripts/complete_liquidity_provision.js --baseTokenId=1 --quoteTokenId=8 --lowestLimit=300 --highestLimit=400 --currentPrice=340 --masterSafe=$MASTER_SAFE --depositBaseToken=0 --depositQuoteToken=0 --numBrackets=10 --network=$NETWORK_NAME
```
=> Xdai deployment

networks.json, package.json, scripts/complete_liquidity_provision.js, scripts/utils/default_yargs.js, scripts/utils/gnosis_safe_server_interactions.js, scripts/utils/internals.js, scripts/utils/liquidity_provision_sanity_checks.js, yarn.lock
This PR makes it so that we can do liquidity provision without requiring the Safe Webinterface (by invoking executeTransaction directly, assuming a single owner safe).
This will be particularly useful on xDAI where the Safe ecosystem won't be ready before earliest the end of next week. The default behaviour didn't change.
Old way still works:
```
yarn truffle exec scripts/complete_liquidity_provision.js --baseTokenId=1 --quoteTokenId=8 --lowestLimit=300 --highestLimit=400 --currentPrice=340 --masterSafe=$MASTER_SAFE --depositBaseToken=0 --depositQuoteToken=0 --numBrackets=10 --network=$NETWORK_NAME
```
But also new way works and leads to executed txs (e.g. [this one](https://blockscout.com/poa/xdai/tx/0x93e5608647859c8f0486f92b9fdee2e52689fc605ff1e4d3e7f5208208b49a17/token-transfers))
``` …
```
=> Allow liquidity provision without Web

scripts/wrapper/withdraw.js, test/scripts/withdraw.js
We have a feature preventing small amounts (<$1) from being withdrawn, since on mainnet this is likely not economically viable. However, this feature heavily relies on a working 1Inch price estimator. This may not work for some tokens such as wxDAI. Also such a limit does not necessarily make sense on other networks where gas fees are low ($1 seems a bit arbitrary and should probably be configurable to begin with). 
We do have an option for the `request_withdraw` script that will ignore this "protection" and withdraw amounts regardless of value. However, the check for small balance not only happens in the amount estimation function ([here](https://github.com/gnosis/dex-liquidity-provision/blob/f80edbdeb3f11c97f400eb0e974815417c37693e/scripts/wrapper/withdraw.js#L141-L149)) but also in …
=> Allow withdrawl of balances < 1$

scripts/claim_withdraw.js, scripts/complete_liquidity_provision.js, scripts/request_withdraw.js, scripts/transfer_funds_to_master.js, scripts/wrapper/withdraw.js, test/scripts/withdraw.js
Similar to #519 but for withdrawals. This will allow us to easily relaunch strategies until the Safe Web is available.
Withdraw my test liquidity (between WETH and wxDAI)
```sh
yarn truffle exec scripts/request_withdraw.js --masterSafe=$MASTER_SAFE --brackets=0x5D6b329918c2BF4d9B722c5c8F8d981E61974d03,0x52033e1F448C69eD6AdDCebF47f9a5836df6395D,0x9A5aB9da6Ee6D9907B19738824C25dfAf0482CD6,0x876EF54A5833DaF55F2c27b4fD098cfdbdb92b70,0x0BdB46E41c80749F5506f51037a981276Dd982E4,0x463Ba08241022F65416a57b428EE32cB25402918,0xf1E115BB04789f85A85f033be932953Cb09DFc72,0xAB795A52D809e4Aa56da23b215Db7663d57CDE3A,0x45d8a3d10cd7Da86Dac21a51B305312Ebf80072d,0x2952bC69739c9534d09525ccCa33950F311CbE88 --tokenIds=1,4 --network=$NETWORK_NAME --executeOnchain --noBalanceCheck
yarn truffle exec …
```
=> [Easy] Allow withdraw scripts to be directly executed onchain

migrations/2_dev_dependencies.js, networks.json, scripts/airdrop.js, scripts/deposit.js, scripts/testing/setup_thegraph_data.js, scripts/transfer_approve_deposit.js, scripts/utils/calculate_fleet_addresses.js, scripts/utils/dependencies.js, scripts/utils/internals.js, scripts/utils/strategy_simulator.js, scripts/utils/trading_strategy_helpers.js, scripts/utils/verify_scripts.js, scripts/wrap_eth.js, test/dfusion_multi_safes.js, test/fleet_factory.js, test/fleet_factory_deterministic.js, test/scripts/deposit.js, test/scripts/test_airdrop.js, test/scripts/withdraw.js, test/verification_script.js
As discussed on #518 relying on our local compilation of dependent contracts can be error-prone if we e.g. update the GnosisSafe contract but don't remember to do a full local "re-migration".
This PR is a first step to removing our external dependecies (Safe, SafeFactory, MultiSend, BatchExchange) by using the artefact from the npm package directly.
The challenge with this was that in tests, we need a locally deployed instance (so that we can call GnosisSafe.deployed even on ganache). To achieve this we now use artefactor to write the locally deployed json back into the dependent npm folder.
Also tagging @rmeissner as he might have some idea of how to better accomplish what we want.
complete liquidity provision still works on Rinkeby + unit tests pass
=> Use GnosisSafe npm artefact instead of local compilation

scripts/balance_viewer.js
This PR adjusts the balance viewer script to allow emitting an error if a given `lowBalanceThreshold` is not achieved by the sum of all brackets that were checked.
This will allow us to create a cron job monitoring our brackets and emitting an `stderr` message (which we can forward into slack) if a certain strategy is no longer funded.
For the shell script I'm envisioning something like
```sh
#!/bin/bash
INPUT=`curl -s https://gist.githubusercontent.com/fleupold/d1d1b7ade5be110a243bc0b60c4510fd/raw/42b145e5e2c1ebfc43a98bf877d5bccb68562300/watch_brackets.tsv`
NETWORK=mainnet
THRESHOLD=1000
OLDIFS=$IFS
IFS=' '
while read strategy brackets
do
yarn truffle exec scripts/balance_viewer.js --network $NETWORK --lowBalanceThreshold $THRESHOLD --brackets $brackets --alias $strategy
done <<< $INPUT …
```
=> Adjust BalanceViewer to alert on lowBalanceThreshold
